export const GET_QUESTIONS_REQUEST = "GET_QUESTIONS_REQUEST";
export const GET_QUESTIONS_REQUEST_SUCCESS = "GET_QUESTIONS_REQUEST_SUCCESS";
export const GET_QUESTIONS_REQUEST_FAIL = "GET_QUESTIONS_REQUEST_FAIL";

export const CHANGE_USER_ANSWER = "CHANGE_USER_ANSWER";
export const CLEAR_USER_ANSWERS = "CLEAR_USER_ANSWERS";
export const CHECK_USER_ANSWERS = "CHECK_USER_ANSWERS";
